apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec: 
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - ConfigMapRef:
        name: configmap



# env:
    #   - name: course
    #     valueFrom:
    #       configMapKeyRef:
    #         name: configmap # name of the config map you are referring to
    #         key: course # env.name and config map key name can be different
    #   - name: student
    #     valueFrom:
    #       configMapKeyRef:
    #         name: configmap
    #         key: student
